### ISSUE TITLE
ソケット通信実装

### ISSUE THREAD

**Issue by spre55** [XMLPro/TweetDungeonProject#1]
# ソケット

**Comment by hi-ra** [comment]
# ソケットとは

ソケットである. それ故, ソケットなのである

**Comment by mneko22** [comment]
<h1>なるほど、私はソケットのソの字も理解していなかったのか・・・</h1>

**Comment by mneko22** [comment]
今日の成果物
https://gist.github.com/30de726268aecbf4b958.git

**Comment by mneko22** [comment]
メッセージを連投するとIllegalArgumentExceptionが投げられて処理が停止します。理由はわかりません。
Session.sendText(String);で怒られているみたいですが、
https://docs.oracle.com/javaee/7/api/javax/websocket/RemoteEndpoint.Async.html
では引数がnullの場合にIllegalArgumentExceptionが投げられるので意味不です。
