### ISSUE TITLE
ユーザー側での重複ツイートが発生する問題

### ISSUE THREAD

**Issue by sinshutu** [XMLPro/TweetDungeonProject#8]
現在出ている解決策は、
- botを立ててリプライで対応する
  - bot側でツイート回数制限がある
- つぶやきから上下左右の意味を見出す
  - わかりにくい?

他に解決策あれば提案お願いします

**Comment by matsuneko22** [comment]
てすと
2015/11/18 17:12 "suzuki" <notifications@github.com>:

**Comment by mneko22** [comment]
命令＋時間をハッシュ値に変換して、それらを選んで投稿してもらうとか？
例えば上+9:00をハッシュ値に変換して fe1153bb500fca8db0bdc0f9f7969967
長いからダメか・・・

**Comment by sinshutu** [comment]
ツイッター使うとapi制限でうまくいかなさそうなので、操作用のクライアントページも容易してそこから操作してもらった方が良いかな？

**Comment by mneko22** [comment]
クライアント作っちゃうとツイッター使う意味が無くなる気がする。
ゲームに参加している全員がサイトにアクセスして迷路が見ているということを条件として、命令を上下左右ではなくて、ターン後とに上の人は猫を・・・と何らかの単語に置き換えてツイートさせてみるのもおもしろいんじゃない？

**Comment by sinshutu** [comment]
すまん、説明足りてなかった。
ツイッターにこだわってるせいで、余分な機能がついたりとか元々の
「なんかすぐできて面白い」
から離れてる気がする。
なので、この際ツイッター使わない方向性も有りなんじゃないかと

ツイッターの代わりに操作用のクライアントページを用意して、
迷路自体も他のページで見れるようにする感じ
迷路自体は、最悪クライアント側から操作画面と同時に見れなくても良いかなと

**Comment by sinshutu** [comment]
できるそうな解決策をすべて実装する。
- ツイッターのハッシュダグから取得
- コマンド投稿用のクライアント実装
- ツイッターと連携するクライアント実装
